---
title: "matplotlib demo"
format:
  html:
    code-fold: true
kernel: python3
---

```{python}
# Libraries Set Up

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels as sm
import branca.colormap as cmp
import folium
import shapely
import plotly.express as px
from matplotlib import colors
```

# 1. Introduction

Group: 
- Tourism 

Members: 
- Alyazid Alhumaydani
- Ibrahim Algharbi
- Rawan Aljuhani
- Rehab Alaswad

# 1a) About the dataset. (maybe also about Airbnb)

Our dataset comes from Inside Airbnb:

It's a site that scapes Airbnb's website for its listing's detials

“Inside Airbnb is a mission driven project that provides data and advocacy about Airbnb's impact on residential communities." - Inside Airbnb


# 1b) Why did we choose Canada.

- Familiarity 
 Our group members are more fimilair with Canada than our other options

- Language
We didn't want to deal with translating our dataset

- Dataset Size
The Size of the dataset was sufficient (13621 listings)

# 1c) Our Scenario
<>

```{python}
# Import Data frames

# Canada, Quebec City Dataframe (Main City)
#df, summary data frame
df=pd.read_csv('../data/canada/listings.csv')
#dfd, detailed data frame
dfd=pd.read_csv('../data/canada/detailed_listing.csv')
# review score correlation
dfr = dfd.iloc[:,61:67]
# Sorts and ranks neighborhood by mean price 
neig = df[['price','neighbourhood']].groupby('neighbourhood').mean()
neig = neig.sort_values('price')
neig['rank'] = np.arange(len(neig)) + 1
neig = neig.reset_index(level=0)
```


# 2 EDA

# 2a) Presenting the data.

# 2b) Missing value.

# 2c) How did we clean the data.


```{python}
# Remove coloumn 'neighbourhood_group' and 'license'  because it's all NaN
df.drop(['neighbourhood_group','license'], axis=1, inplace=True)
```


# 2d) Removed outlier.

```{python}

```

# 3 Results:

# 3a Visualizing the Listings' locations

```{python}
# Mapping without folium

# Set bounds
BBox = ((df.longitude.min(),   df.longitude.max(), df.latitude.min(), df.latitude.max()))
# Import Image
ruh_m = plt.imread('../data/canada/map.png')
# Plot Data on Map (Draft v1)
fig, ax = plt.subplots(figsize = (10,10))
ax.scatter(df.longitude, df.latitude, zorder=1, alpha= 0.2, c='b', s=10)
ax.set_title('Plotting Spatial Data on Montreal Map')
ax.set_xlabel('Latitude')
ax.set_label('Longitude')
ax.set_xlim(BBox[0],BBox[1])
ax.set_ylim(BBox[2],BBox[3])
ax.imshow(ruh_m, zorder=0, extent = BBox, aspect= 'equal')
```

# 3b 
```{python}

```
# 3c
```{python}

```
# 3d
```{python}
# Room Type Bar Plot

plot3=sns.barplot(x='room_type', y='price',data=df)
plot3.set(xlabel='Room Type', ylabel='Average Price',title='Room Type Average Price in Montreal')
plt.show()
```

<We show our graphs and plots>




```{python}

```



# 4 Further Research

<Research Article Recommondations>

# Conclusion

